In [1]:
# importing Library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

In [2]:
# read dataset
df=pd.read_csv("Advertising_data.csv")
df.tail()

User ID  Gender   Age  EstimatedSalary  Purchased
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

In [3]:
# handling missing values
df.isnull().any().sum()

0

In [4]:
# feature selection
# training and test set 

X=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values

In [5]:
# spilting train and test dataset
X_train , X_test , y_train , y_test =train_test_split( X, y , test_size=0.30, random_state=10)

In [6]:
# feature scalling
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)

# SVM Classifier

In [7]:
# create svm classifier 
svm_classifier=SVC(kernel="linear",random_state=0)
svm_classifier.fit(X_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=0,
  shrinking=True, tol=0.001, verbose=False)

In [8]:
# Predicting the Test set results
y_pred=svm_classifier.predict(X_test)


In [9]:
# making a confusion matricx
cm=confusion_matrix(y_test,y_pred)
cm

array([[75,  8],
       [ 7, 30]], dtype=int64)

In [10]:
accuracy=accuracy_score(y_test,y_pred)
accuracy

0.875

In [11]:
# Applying Grid Search to find the best model and the best parameters

parameters = [{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
              {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]}]
grid_search = GridSearchCV(estimator = svm_classifier,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 10,
                           n_jobs = -1)
grid_search = grid_search.fit(X_train, y_train)


D:\python\lib\site-packages\sklearn\model_selection\_search.py:841: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


In [12]:
accuracy_grid=grid_search.best_score_
accuracy_grid

0.9178571428571428

In [13]:
grid_search.best_params_

{'C': 1, 'gamma': 0.8, 'kernel': 'rbf'}

In [14]:
# after grid search classifier
svm_rbf_classifier=SVC(kernel="rbf", gamma=0.3,C=10)
svm_rbf_classifier.fit(X_train,y_train)

SVC(C=10, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.3, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [15]:
grid_y_pred=svm_rbf_classifier.predict(X_test)

In [16]:
cm_grid=confusion_matrix(y_test,grid_y_pred)
cm_grid

array([[74,  9],
       [ 2, 35]], dtype=int64)

In [17]:
grid_accuracy=accuracy_score(y_test,grid_y_pred)
grid_accuracy

0.9083333333333333

# KNeighborsClassifier

In [18]:


from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [19]:
kn_classifier=KNeighborsClassifier(n_neighbors=10)
kn_classifier.fit(X_train,y_train)
kn_y_pred=kn_classifier.predict(X_test)
kn_classifier_cm=confusion_matrix(y_test,kn_y_pred)
kn_classifier_cm

array([[75,  8],
       [ 2, 35]], dtype=int64)

In [20]:
kn_classifier_accuracy=accuracy_score(y_test,kn_y_pred)
kn_classifier_accuracy

0.9166666666666666

# LogisticRegression Classifier

In [21]:
logistic_classifier=LogisticRegression()
logistic_classifier.fit(X_train,y_train)
logreg_y_pred=logistic_classifier.predict(X_test)
logreg_cm=confusion_matrix(y_test,logreg_y_pred)
logreg_cm

D:\python\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


array([[75,  8],
       [ 7, 30]], dtype=int64)

In [22]:
logreg_accuracy=accuracy_score(y_test,logreg_y_pred)
logreg_accuracy

0.875

# Model Selection and Cross Validation

In [31]:
print(cross_val_score(svm_rbf_classifier , X , y , scoring ="accuracy", cv=10))
print("Mean= "+str(cross_val_score(svm_rbf_classifier , X , y , cv=10, scoring ="accuracy",).mean()))

[0.75609756 0.65853659 0.65853659 0.7        0.725      0.675
 0.65       0.64102564 0.61538462 0.74358974]
Mean= 0.6823170731707318


In [32]:
print(cross_val_score kn_classifier, X , y , scoring ="accuracy", cv=10))
print("Mean= "+str(cross_val_score(kn_classifier , X , y , cv=10, scoring ="accuracy",).mean()))

SyntaxError: invalid syntax (<ipython-input-32-74622dab455e>, line 1)

In [33]:
print(cross_val_score(logistic_classifier, X , y , scoring ="accuracy", cv=10))
print("Mean= "+str(cross_val_score(logistic_classifier, X , y , cv=10, scoring ="accuracy",).mean()))

[0.68292683 0.63414634 0.63414634 0.65       0.65       0.65
 0.65       0.64102564 0.64102564 0.66666667]
Mean= 0.6499937460913072


D:\python\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
D:\python\lib\site-packages\sklearn\linear_mo